---
kind: pipeline
name: default

steps:
- name: backend
  image: golang
  environment:
    USERNAME:
      from_secret: username
  commands:
  - go build
  - go test
  - echo $USERNAME
  - echo $USERNAME > a.txt
  - cat a.txt
